<?php

$sLangName = 'Deutsch';
$aLang = [
    'charset'                          => 'UTF-8',

    'SHOP_MODULE_GROUP_COMPUTOP_GENERAL'                    => 'General',
    'SHOP_MODULE_GROUP_COMPUTOP_CREDITCARD'                 => 'Kreditkarte',
    'SHOP_MODULE_GROUP_COMPUTOP_PAYPAL'                     => 'PayPal',
    'SHOP_MODULE_GROUP_COMPUTOP_PAYPALEXPRESS'              => 'PayPal Express',
    'SHOP_MODULE_GROUP_COMPUTOP_DIRECTDEBIT'                => 'Lastschrift',
    'SHOP_MODULE_GROUP_COMPUTOP_KLARNA'                     => 'Klarna',
    'SHOP_MODULE_GROUP_COMPUTOP_AMAZONPAY'                  => 'Amazon',
    'SHOP_MODULE_GROUP_COMPUTOP_IDEAL'                      => 'Ideal',
    'SHOP_MODULE_GROUP_COMPUTOP_RATEPAYDIRECTDEBIT'         => 'Ratepay Lastschrift',

    'SHOP_MODULE_merchantID'                                => 'MerchantID',
    'SHOP_MODULE_mac'                                       => 'MAC',
    'SHOP_MODULE_blowfishPassword'                          => 'Passwort',
    'SHOP_MODULE_debuglog'                                  => 'Debug Protokoll',
    'SHOP_MODULE_debuglog_inactive'                         => 'keine Protokollierung',
    'SHOP_MODULE_debuglog_active'                           => 'Protokollierung',
    'SHOP_MODULE_debuglog_extended'                         => 'erweiterte Protokollierung',
    'SHOP_MODULE_encryption'                                => 'Verschlüsselung',
    'SHOP_MODULE_encryption_blowfish'                       => 'Blowfish Verschlüsselung (Standard)',
    'SHOP_MODULE_encryption_aes'                            => 'AES Verschlüsselung',
    'SHOP_MODULE_refnr_prefix'                              => 'Referenznummer Pr&auml;fix',
    'SHOP_MODULE_refnr_suffix'                              => 'Referenznummer Suffix',

    'SHOP_MODULE_creditCardMode'                            => 'Kreditkarte - Modus',
    'SHOP_MODULE_creditCardMode_IFRAME'                     => 'IFrame',
    'SHOP_MODULE_creditCardMode_SILENT'                     => 'Silent Mode',
    'SHOP_MODULE_creditCardMode_PAYMENTPAGE'                => 'Payment Page',
    'SHOP_MODULE_creditCardTestMode'                        => 'Kreditkarte - Test-Modus',
    'SHOP_MODULE_creditCardSilentModeBrandsVisa'            => 'Kreditkarte - Visa (Silent Mode)',
    'SHOP_MODULE_creditCardSilentModeBrandsMaster'          => 'Kreditkarte - MasterCard (Silent Mode)',
    'SHOP_MODULE_creditCardSilentModeBrandsAmex'            => 'Kreditkarte - American Express (Silent Mode)',
    'SHOP_MODULE_creditCardCaption'                         => 'Kreditkarte - Capture Modus',
    'SHOP_MODULE_creditCardCaption_AUTO'                    => 'Automatisch',
    'SHOP_MODULE_creditCardCaption_MANUAL'                  => 'Manuell',
    'SHOP_MODULE_creditCardAcquirer'                        => 'Kreditkarte - Acquirer',
    'SHOP_MODULE_creditCardAcquirer_GICC'                   => 'GICC',
    'SHOP_MODULE_creditCardAcquirer_CAPN'                   => 'CAPN',
    'SHOP_MODULE_creditCardAcquirer_Omnipay'                => 'Omnipay',
    'SHOP_MODULE_creditCardTemplate'                        => 'Kreditkarte - Template Name',

    'SHOP_MODULE_paypalCaption'                             => 'Paypal - Capture Modus',
    'SHOP_MODULE_paypalCaption_AUTO'                        => 'Automatisch',
    'SHOP_MODULE_paypalCaption_MANUAL'                      => 'Manuell',

    'SHOP_MODULE_paypalExpressTestMode'                     => 'PayPal Express - Test Modus',
    'SHOP_MODULE_paypalExpressCaption'                      => 'PayPal Express - Capture Modus',
    'SHOP_MODULE_paypalExpressCaption_AUTO'                 => 'Automatisch',
    'SHOP_MODULE_paypalExpressCaption_MANUAL'               => 'Manuell',
    'SHOP_MODULE_paypalExpressClientID'                     => 'PayPal Express - Client-ID',
    'SHOP_MODULE_paypalExpressMerchantID'                   => 'PayPal Express - Merchant-ID',
    'SHOP_MODULE_paypalExpressPartnerAttributionID'         => 'Computop - Partner-Attribution-ID',

    'SHOP_MODULE_lastschriftCaption'                        => 'Lastschrift - Capture Modus',
    'SHOP_MODULE_lastschriftCaption_AUTO'                   => 'Automatisch',
    'SHOP_MODULE_lastschriftCaption_MANUAL'                 => 'Manuell',

    'SHOP_MODULE_klarnaaccount'                             => 'Klarna Konto',

    'SHOP_MODULE_amazonpayMerchantId'                       => 'AmazonPay - MerchantId',
    'SHOP_MODULE_amazonpayPubKeyId'                         => 'AmazonPay - Public Key Id',
    'SHOP_MODULE_amazonLiveMode'                            => 'Amazon Modus',
    'SHOP_MODULE_amazonLiveMode_Live'                       => 'Live',
    'SHOP_MODULE_amazonLiveMode_Test'                       => 'Test',
    'SHOP_MODULE_amazonCaptureType'                         => 'Amazon Capture Modus',
    'SHOP_MODULE_amazonCaptureType_AUTO'                    => 'Automatisch',
    'SHOP_MODULE_amazonCaptureType_MANUAL'                  => 'Manuell',
    'SHOP_MODULE_amazonButtonColor'                         => 'AmazonPay - Button Farbe',
    'SHOP_MODULE_amazonButtonColor_Gold'                    => 'Gold',
    'SHOP_MODULE_amazonButtonColor_LightGray'               => 'LightGray',
    'SHOP_MODULE_amazonMarketplace'                         => 'Verwendeter Amazon Marketplace',
    'SHOP_MODULE_amazonMarketplace_EU'                      => 'EU',
    'SHOP_MODULE_amazonMarketplace_UK'                      => 'UK',
    'SHOP_MODULE_amazonMarketplace_US'                      => 'US',
    'SHOP_MODULE_amazonMarketplace_JP'                      => 'JP',

    'SHOP_MODULE_idealDirektOderUeberSofort'                => 'iDEAL - Dienst',
    'SHOP_MODULE_idealDirektOderUeberSofort_DIREKT'         => 'iDEAL Direkt',
    'SHOP_MODULE_idealDirektOderUeberSofort_PPRO'           => 'via PPRO',

    'SHOP_MODULE_ratepayDirectDebitRequestBic'              => 'BIC abfragen',

    'HELP_SHOP_MODULE_blMollieShowIcons'                    => 'Ihre Merchant Id (Benutzername)',
    'HELP_SHOP_MODULE_mac'                                  => 'Ihr HMAC-Key',
    'HELP_SHOP_MODULE_blowfishPassword'                     => 'Ihr Verschlüsselungs-Passwort',
    'HELP_SHOP_MODULE_debuglog'                             => 'Erzeugt eine Log Datei "FatchipCTPayment_.log" mit Debug Ausgaben im Oxid Protokollverzeichnis.',
    'HELP_SHOP_MODULE_encryption'                           => 'Art der verwendeten Verschlüsselung.<br>Blowfish Verschlüsselung wird vom Computop Support als Standard eingerichtet.<br>Sollte die Blowfish Verschlüsselung (bf-cbc) bei Ihrem Hoster nicht verfügbar sein, wenden Sie sich bitte an den Computop Support und lassen Sie AES aufschalten.<br>Wenn seitens Computop AES aktiviert wurde, stellen Sie auf AES um.',

    'HELP_SHOP_MODULE_creditCardMode'                       => '<b>IFrame</b>: The creditcard form will be displayed after clicking "confirm payment" in an iframe<BR><b>Silent Mode</b>: The creditcard form will be displayed on the "complete order" page.<BR><b>Payment Page</b>: Credit card details are entered in a blank page after clicking on "Order payment".',
    'HELP_SHOP_MODULE_creditCardCaption'                    => '<b>AUTO</b>: Reserved amounts will be captured automatically.<BR><b>MANUAL</b>: Reserverd amounts have to be captured manuelly in the shop backend.</p>',
    'HELP_SHOP_MODULE_creditCardAcquirer'                   => '<b>GICC</b>: Concardis, B+S Card Service, EVO Payments, American Express, Elavon, SIX Payment Service<BR><b>CAPN</b>: American Express<BR><b>Omnipay</b>: EMS payment solutions, Global Payments, Paysquare',
    'HELP_SHOP_MODULE_creditCardTemplate'                   => 'Name of the XSLT-file with your individual payment form layout. If you want to use the responsive computop template for mobile devices, please use the template name „ct_responsive“.',

    'HELP_SHOP_MODULE_paypalCaption'                        => '<p>Determines whether the requested amount is collected immediately or at a later date. <br><b>Important:<br>Please contact Computop Support for Manual to clarify the different application options.</b></p>',

    'HELP_SHOP_MODULE_paypalExpressTestMode'                => 'Test Modus',
    'HELP_SHOP_MODULE_paypalExpressCaption'                 => 'Bestimmt, ob der angefragte Betrag sofort oder erst später eingezogen wird. <br><b>Wichtig:<br>Bitte kontaktieren Sie den Computop Support für Manual, um die unterschiedlichen Einsatzmöglichkeiten abzuklären.</b>',
    'HELP_SHOP_MODULE_paypalExpressClientID'                => 'PaypalExpress Client-ID.',
    'HELP_SHOP_MODULE_paypalExpressMerchantID'              => 'PaypalExpress Merchant-ID.',
    'HELP_SHOP_MODULE_paypalExpressPartnerAttributionID'    => 'Computop Partner-Attribution-ID.',

    'HELP_SHOP_MODULE_lastschriftCaption'                   => '<b>AUTO</b>: Reservierte Beträge werden sofort automatisch eingezogen.<BR><b>MANUAL</b>: Geldeinzüge werden von Ihnen manuell im Shopbackend durchgeführt.</p>',

    'HELP_SHOP_MODULE_klarnaaccount'                        => 'Das zu benutzende Klarna Konto.',

    'HELP_SHOP_MODULE_amazonpayMerchantId'                  => 'Ihre Amazonpay MerchantId',
    'HELP_SHOP_MODULE_amazonpayPubKeyId'                    => 'Ihre Amazonpay Public Key Id',
    'HELP_SHOP_MODULE_amazonLiveMode'                       => 'AmazonPay im Live oder Testmodus benutzen',
    'HELP_SHOP_MODULE_amazonCaptureType'                    => '<b>Automatisch</b>: Reservierte Beträge werden automatisch eingezogen.<BR><b>Manuell</b>: Geldeinzüge werden von Ihnen manuell im Shopbackend durchgeführt.',
    'HELP_SHOP_MODULE_amazonButtonColor'                    => 'Farbe des Amazon Buttons<BR>Das Aussehen der verschiedenen Buttons.<BR>Klicken Sie links auf den Link "AmazonPay - Button Farbe"',

    'HELP_SHOP_MODULE_idealDirektOderUeberSofort'           => 'Wählen Sie hier Ihre Anbindung an iDeal aus - direkt oder über PPRO.',

    'FATCHIP_COMPUTOP_PAYMENT'          => 'Computop Zahlarten Einstellungen',
    'fatchip-computop-payments'        => 'Computop',
    'FATCHIP_COMPUTOP_PAYMENTS_CONFIG' => 'Konfiguration',
    'FATCHIP_COMPUTOP_PAYMENTS_APILOG' => 'API Logs',
    'FATCHIP_COMPUTOP_ERR_CONF_INVALID' => 'Konfiguration inkorrekt',
    'FATCHIP_COMPUTOP_CONF_VALID'      => 'Konfiguration korrekt',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_ID' => 'ID',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_REQUEST' => 'Request',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_RESPONSE' => 'Response',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_CREATION_DATE' => 'Zeit',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_PAYMENT_NAME' => 'Zahlart',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_REQUEST_DETAILS' => 'Request Details',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_RESPONSE_DETAILS' => 'Response Details',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_RESPONSE_TRANS_ID' => 'TransId',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_RESPONSE_X_ID' => 'XId',
    'FATCHIP_COMPUTOP_REMARK' => 'Computop Mitteilung',
    'FATCHIP_COMPUTOP_GENERAL_SETTINGS' => 'General',
    'FATCHIP_COMPUTOP_CREDIT_CARD_SETTINGS' => 'Kreditkarte',
    'FATCHIP_COMPUTOP_IDEAL_SETTINGS' => 'Ideal',
    'FATCHIP_COMPUTOP_PAYPAL_SETTINGS' => 'Paypal',
    'FATCHIP_COMPUTOP_PAYPALEXPRESS_SETTINGS' => 'PayPal Express',
    'FATCHIP_COMPUTOP_RATEPAYDIRECTDEBIT_SETTINGS' => 'Ratepay Lastschrift',
    'FATCHIP_COMPUTOP_DIRECT_DEBIT_SETTINGS' => 'Lastschrift',
    'FATCHIP_COMPUTOP_AMAZON_SETTINGS' => 'Amazon',
    'FATCHIP_COMPUTOP_KLARNA_SETTINGS' => 'Klarna',
    'FATCHIP_COMPUTOP_IDEAL_ISSUERS' => 'Banken wurden erfolgreich aktualisiert',
    'FATCHIP_COMPUTOP_IDEAL_ISSUERS_ERROR' => 'Fehler beim Aktualisieren der Banken',
    'fatchip_computop_ADMIN_API_LOGS_SELECT_ENTRY' => 'Bitte Log auswählen',
    'FATCHIP_COMPUTOP_PAYMENT_TYPE' => 'Zahlungsart',
    'FATCHIP_COMPUTOP_EXTERNAL_TRANSACTION_ID' => 'Externe TransaktionsId',
    'FATCHIP_COMPUTOP_ORDER_REMARK' => 'Notiz',
    'FATCHIP_COMPUTOP_CAPTURE_TITLE' => 'Beitragseinzug',
    'FATCHIP_COMPUTOP_NO_COMPUTOP_PAYMENT' => 'Keine Computop Bestellung',
    'FATCHIP_COMPUTOP_HEADER_SINGLE_PRICE' => 'Einzelpreis',
    'FATCHIP_COMPUTOP_CAPTURE_SUBMIT' => 'Beitrag einziehen',
    'FATCHIP_COMPUTOP_ORDER_SETTINGS' => 'Computop',
    'FATCHIP_COMPUTOP_PAYMENT_DETAILS' => 'Computop Bestelldetails',
    'FATCHIP_COMPUTOP_ORDER_CAPTURED_AMOUNT' => 'Eingezogener Betrag',
    'FATCHIP_COMPUTOP_ORDER_PAYID' => 'PayId',
    'FATCHIP_COMPUTOP_ORDER_REFUND_AMOUNT' => 'Gutgeschriebener Betrag:',
    'FATCHIP_COMPUTOP_REFUND_SUBMIT' => 'Bestellung komplett gutschreiben',
    'FATCHIP_COMPUTOP_REFUND_ARTICLES_SUBMIT' => 'Ausgewählte Artikel gutschreiben',
    'COMPUTOP_ARTICLE_REFUNDED' => 'Ist gutgeschrieben ?',
    'COMPUTOP_ARTICLE_REFUNDED_YES' => 'Ja',
    'COMPUTOP_ARTICLE_REFUNDED_NO' => 'Nein',
    'COMPUTOP_ARTICLE_REFUNDED_NO_ARTICLES_TO_REFUND' => 'Alle Artikel bereit gutgeschrieben',
    'COMPUTOP_ARTICLE_REFUNDED_NO_ARTICLES_CHECKED'   => 'Bitte Artikel auswählen',
    'FATCHIP_COMPUTOP_CAPTURE_SUBMIT_COMPLETE' => 'Bestellung komplett gutgeschrieben.',
    'COMPUTOP_REFUND_SUCCESS' => 'Gutschrift erfolgreich erstellt.',
    'FATCHIP_COMPUTOP_REFUND' => 'Gutschrift:',
    'FATCHIP_COMPUTOP_REFUND_ALL' => 'Gutschrift komplett:',
    'FATCHIP_COMPUTOP_PAYMENTS_APILOG_MAIN' => 'API Logs Details',
];
