<?php

$sLangName = 'Deutsch';
$aLang = [
    'charset'                          => 'UTF-8',
    'FATCHIP_COMPUTOP_PAYMENT'          => 'Computop Zahlarten Einstellungen',
    'fatchip-computop-payments'        => 'Computop',
    'FATCHIP_COMPUTOP_PAYMENTS_CONFIG' => 'Konfiguration',
    'FATCHIP_COMPUTOP_PAYMENTS_APILOG' => 'API Logs',
    'FATCHIP_COMPUTOP_ERR_CONF_INVALID' => 'Konfiguration inkorrekt',
    'FATCHIP_COMPUTOP_CONF_VALID'      => 'Konfiguration korrekt',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_ID' => 'ID',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_REQUEST' => 'Request',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_RESPONSE' => 'Response',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_CREATION_DATE' => 'Zeit',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_PAYMENT_NAME' => 'Zahlart',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_REQUEST_DETAILS' => 'Request Details',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_RESPONSE_DETAILS' => 'Response Details',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_RESPONSE_TRANS_ID' => 'TransId',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_RESPONSE_X_ID' => 'XId',
    'FATCHIP_COMPUTOP_REMARK' => 'Computop Mitteilung',
    'FATCHIP_COMPUTOP_GENERAL_SETTINGS' => 'General',
    'FATCHIP_COMPUTOP_CREDIT_CARD_SETTINGS' => 'Kreditkarte',
    'FATCHIP_COMPUTOP_IDEAL_SETTINGS' => 'Ideal',
    'FATCHIP_COMPUTOP_PAYPAL_SETTINGS' => 'Paypal',
    'FATCHIP_COMPUTOP_DIRECT_DEBIT_SETTINGS' => 'Lastschrift',
    'FATCHIP_COMPUTOP_AMAZON_SETTINGS' => 'Amazon',
    'FATCHIP_COMPUTOP_KLARNA_SETTINGS' => 'Klarna',
    'FATCHIP_COMPUTOP_IDEAL_ISSUERS' => 'Banken wurden erfolgreich aktualisiert',
    'FATCHIP_COMPUTOP_IDEAL_ISSUERS_ERROR' => 'Fehler beim Aktualisieren der Banken',
    'fatchip_computop_ADMIN_API_LOGS_SELECT_ENTRY' => 'Bitte Log auswählen',
];
