<?php

$sLangName = 'English';

$aLang = [
    'charset'                          => 'UTF-8',
    'FATCHIP_COMPUTOP_PAYMENT'          => 'Computop Zahlarten Einstellungen',
    'fatchip-computop-payments'        => 'Computop',
    'FATCHIP_COMPUTOP_PAYMENTS_CONFIG' => 'Konfiguration',
    'FATCHIP_COMPUTOP_PAYMENTS_APILOG' => 'API Logs',
    'FATCHIP_COMPUTOP_ERR_CONF_INVALID' => 'Konfigurationsfehler',
    'FATCHIP_COMPUTOP_CONF_VALID'      => 'Konfiguration funktioniert',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_ID' => 'ID',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_REQUEST' => 'Anfrage',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_RESPONSE' => 'Antwort',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_CREATION_DATE' => 'Zeit',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_PAYMENT_NAME' => 'Zahlart',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_REQUEST_DETAILS' => 'Anfrage Details',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_RESPONSE_DETAILS' => 'Antwort Details',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_RESPONSE_TRANS_ID' => 'TransId',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_RESPONSE_X_ID' => 'XId',
    'FATCHIP_COMPUTOP_REMARK' => 'Computop notice',
    'FATCHIP_COMPUTOP_GENERAL_SETTINGS' => 'General',
    'FATCHIP_COMPUTOP_CREDIT_CARD_SETTINGS' => 'Kreditkarte',
    'FATCHIP_COMPUTOP_IDEAL_SETTINGS' => 'Ideal',
    'FATCHIP_COMPUTOP_PAYPAL_SETTINGS' => 'Paypal',
    'FATCHIP_COMPUTOP_DIRECT_DEBIT_SETTINGS' => 'Direct Debit',
    'FATCHIP_COMPUTOP_PAYDIREKT_SETTINGS' => 'PayDirekt',
    'FATCHIP_COMPUTOP_AMAZON_SETTINGS' => 'Amazon',
    'FATCHIP_COMPUTOP_BONITAET_SETTINGS' => 'Bonität',
    'FATCHIP_COMPUTOP_KLARNA_SETTINGS' => 'Klarna',
];
