<?php

$sLangName = 'English';

$aLang = [
    'charset'                          => 'UTF-8',
    'FATCHIP_COMPUTOP_PAYMENT'          => 'Computop Payments Configuration',
    'fatchip-computop-payments'        => 'Computop',
    'FATCHIP_COMPUTOP_PAYMENTS_CONFIG' => 'Configuration',
    'FATCHIP_COMPUTOP_PAYMENTS_APILOG' => 'API Logs',
    'FATCHIP_COMPUTOP_ERR_CONF_INVALID' => 'Incorrect Configuration',
    'FATCHIP_COMPUTOP_CONF_VALID'      => 'Correct Configuration',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_ID' => 'ID',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_REQUEST' => 'Request',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_RESPONSE' => 'Response',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_CREATION_DATE' => 'Time',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_PAYMENT_NAME' => 'Payment Method',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_REQUEST_DETAILS' => 'Request Details',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_RESPONSE_DETAILS' => 'Response Details',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_RESPONSE_TRANS_ID' => 'TransId',
    'FATCHIP_COMPUTOP_PAYMENT_API_LOG_RESPONSE_X_ID' => 'XId',
    'FATCHIP_COMPUTOP_REMARK' => 'Computop notice',
    'FATCHIP_COMPUTOP_GENERAL_SETTINGS' => 'General',
    'FATCHIP_COMPUTOP_CREDIT_CARD_SETTINGS' => 'Credit Card',
    'FATCHIP_COMPUTOP_IDEAL_SETTINGS' => 'Ideal',
    'FATCHIP_COMPUTOP_PAYPAL_SETTINGS' => 'Paypal',
    'FATCHIP_COMPUTOP_DIRECT_DEBIT_SETTINGS' => 'Direct Debit',
    'FATCHIP_COMPUTOP_AMAZON_SETTINGS' => 'Amazon',
    'FATCHIP_COMPUTOP_KLARNA_SETTINGS' => 'Klarna',
    'FATCHIP_COMPUTOP_IDEAL_ISSUERS' => 'Bank list updated successfully',
    'FATCHIP_COMPUTOP_IDEAL_ISSUERS_ERROR' => 'An error occurred while updating the bank list',
    'fatchip_computop_ADMIN_API_LOGS_SELECT_ENTRY' => 'Please select a log entry',
    'FATCHIP_COMPUTOP_PAYMENT_TYPE' => 'Payment Type',
    'FATCHIP_COMPUTOP_EXTERNAL_TRANSACTION_ID' => 'External Transaction ID',
    'FATCHIP_COMPUTOP_ORDER_REMARK' => 'Note',
    'FATCHIP_COMPUTOP_CAPTURE_TITLE' => 'Capture',
    'FATCHIP_COMPUTOP_NO_COMPUTOP_PAYMENT' => 'This is not a Computop Order',
    'FATCHIP_COMPUTOP_HEADER_SINGLE_PRICE' => 'Unit Price',
    'FATCHIP_COMPUTOP_CAPTURE_SUBMIT' => 'Capture Amount',
    'FATCHIP_COMPUTOP_ORDER_SETTINGS' => 'Computop',
    'FATCHIP_COMPUTOP_PAYMENT_DETAILS' => 'Computop Order Details',
    'FATCHIP_COMPUTOP_ORDER_CAPTURED_AMOUNT' => 'Captured Amount',
    'FATCHIP_COMPUTOP_ORDER_PAYID' => 'PayId',
];
